---

- hosts: all
  vars:
    consul_servers: "{{ groups['all'] }}"
    consul_http_address: "{{ ansible_host }}"
    consul_bind_address: "{{ ansible_host }}"
    consul_client_address: "{{ ansible_host }}"
    consul_advertise_address: "{{ ansible_host }}"
    consul_version: 1.2.2
    consul_install_nginx: false
    consul_install_nginx_config: false
    consul_enable_nginx_config: false
    consul_dns_config: true
    consul_recursors: ['8.8.8.8', '8.8.8.4']
    consul_manage_service: true
    consul_is_server: true
    consul_join_at_start: false
    consul_retry_join: true
    consul_datacenter: "dc"
    consul_bootstrap: false
    consul_bootstrap_expect: 3
    consul_port_dns: 53
    consul_use_upstart: false
    consul_use_systemd: true
    consul_home: /srv/consul
    consul_config_file: /etc/consul.json
    consul_leave_on_terminate: false
  roles:
      - consul
