---
# file: patroni-class
- hosts: all
  become: yes
  become_method: sudo
  vars:
    postgres_root: "/srv/postgres"
    patroni_node_name: "pg-{{ inventory_hostname }}"
    patroni_scope: "patroni-class"
    patroni_scope_walg: "patroni-class-walg"
  roles:
    - { role: patroni}
